### ISSUE TITLE
libwkhtmltox using produceForms html form to pdf form does not work

### ISSUE THREAD

**Issue by xiaolei000129** [HakanL/WkHtmlToPdf-DotNet#102]
libwkhtmltox using produceForms html form to pdf form does not work

**Comment by xiaolei000129** [comment]
![image](https://user-images.githubusercontent.com/44334120/224907810-21ad64ab-5acc-4261-ae6c-7ff08190e342.png)
![image](https://user-images.githubusercontent.com/44334120/224907873-76a4294d-c817-4152-a31d-6ddf3688da79.png)

**Comment by HakanL** [comment]
That's something you need to bring up to that project, this project here is just a wrapper for .NET.
