### ISSUE TITLE
Gmail is detecting pdf generated by  WkHtmlToPdf-DotNet as malware

### ISSUE THREAD

**Issue by poncejj** [HakanL/WkHtmlToPdf-DotNet#104]
When I try to send an email with an attached pdf that was generated by WkHtmlToPdfDotNet, it detects that is malicious and block me the mail.

Here is the code I convert the HTML to PDF
`                var doc = new HtmlToPdfDocument()
                {
                    GlobalSettings = {
                        ColorMode = ColorMode.Color,
                        Orientation = orientation,
                        PaperSize = PaperKind.A4,
                        Out = fileName,
                    }
                };

                foreach (var item in pages)
                {
                    var page = new ObjectSettings()
                    {
                        PagesCount = true,
                        WebSettings = { DefaultEncoding = "utf-8" },
                        HtmlContent = item,
                    };

                    doc.Objects.Add(page);
                }

                _converter.Convert(doc);
`
This is the error I got:

![image](https://user-images.githubusercontent.com/45267866/226966400-51f3348b-06da-4f98-922b-06130c8c363a.png)

**Comment by HakanL** [comment]
It's impossible for us to know what causes Gmail to trigger this. Plus this project doesn't manipulate the PDF, this is just a wrapper, if anything it's something you can bring up to the wkhtmltopdf project, but be aware that you will need to include more details as the above screenshot won't indicate why it was blocked.
