### ISSUE TITLE
I didn't use dependency injection. Using static creation would cause the thread to get stuck and new requests to keep getting stuck

### ISSUE THREAD

**Issue by xiaolei000129** [HakanL/WkHtmlToPdf-DotNet#108]
![image](https://user-images.githubusercontent.com/44334120/236743320-4a36c1ec-55af-4413-9707-b738b07eec22.png)

**Comment by xiaolei000129** [comment]
I'm using a static constructor for a static class

**Comment by xiaolei000129** [comment]
It's thread safe. Static constructors are executed only once the first time the class is accessed, and only by one thread in a multithreaded environment. Thus, static constructors initialize data thread-safe.

**Comment by xiaolei000129** [comment]
![image](https://user-images.githubusercontent.com/44334120/237021687-aca1a244-bdbb-45a2-87da-7c0750275af1.png)

![image](https://user-images.githubusercontent.com/44334120/237021775-a3543e3b-5ed1-42e4-8208-ae6932081a78.png)

I was wondering if this was the case, but during the testing process, I found that my expectations met

**Comment by HakanL** [comment]
Looks correct, but please share the code that is causing the problems.

**Comment by xiaolei000129** [comment]
The code above is my code

**Comment by HakanL** [comment]
BTW what do you mean with thread getting stuck? So the PDF generation is single-threaded, so it will only allow one PDF to be generated at a time, when it's finished the next will be processed and so on. It doesn't matter how many threads you'll throw at it, it won't run faster.

**Comment by xiaolei000129** [comment]
The phenomenon is that all timeout freezes as long as the method is called

**Comment by HakanL** [comment]
But the first one will eventually complete or? How large are is the HTML content?

**Comment by xiaolei000129** [comment]
The problem is occasional

**Comment by xiaolei000129** [comment]
html size is uncertain

**Comment by xiaolei000129** [comment]
It shouldn't be very big

**Comment by xiaolei000129** [comment]
I know what the problem is
Because I implemented an htmlto image myself with libwkhtmltox
There may be multiple threads accessing the same libwkhtmltox.dll
The current solution is to copy a set of libwkhtmltox.dll files for htmlto image

**Comment by xiaolei000129** [comment]
Whether you need to support html to image

**Comment by HakanL** [comment]
Yeah, there can only be one instance (per appdomain). Or change your image method to use the same singleton.

**Comment by xiaolei000129** [comment]
Will you provide html to image implementation?

**Comment by xiaolei000129** [comment]
Otherwise I can only have two sets of instances

**Comment by HakanL** [comment]
I don't think it's in this wrapper currently, but if the native library supports it then I'm sure it's possible to add it, feel free to submit PR.

**Comment by xiaolei000129** [comment]
Uh-huh
