### ISSUE TITLE
Not reading settings on alpine

### ISSUE THREAD

**Issue by ozzyDrive** [HakanL/WkHtmlToPdf-DotNet#110]
Hi,

I stumbled on this problem when trying to switch our base image from Debian to Alpine due to security issues and it seems it is replicated in the example https://github.com/HakanL/WkHtmlToPdf-DotNet/blob/master/src/TestConsoleAppDockerAlpine/Dockerfile

The GlobalSettings object passed to HtmlToPdfDocument seem to have no effect on the actual output. I have tried changing the DPI, orientation and paper size. All of these do work in the Debian image as well as running it as a console application.

I have tried different dependencies from different sources but honestly it has just been trial and error. What could it be missing?

**Comment by HakanL** [comment]
Never heard of this before, must be some kind of missing dependency would be my guess, but I can't say what. If you find out feel free to share your findings.

**Comment by jkl83** [comment]
Try disabling SmartShrinking. Worked for me on debian.

![image](https://github.com/HakanL/WkHtmlToPdf-DotNet/assets/135227777/8ee6b785-ffa7-4ca7-848c-ab2ec9e8abf7)
