### ISSUE TITLE
The wkhtmltopdf project that is used, is no longer maintained

### ISSUE THREAD

**Issue by pieterh** [HakanL/WkHtmlToPdf-DotNet#115]
The core of this project (wkhtmltopdf) is no longer maintained.  So consider the current status of the wkhtmltopdf project when starting to use the WkHtmlToPdf-DotNet package and consider migrating if you are already using it.

**Comment by pieterh** [comment]
Nope, not (that are free for opensource projects) that I could find! I found one but seems to be using headless chrome... I'm going back to the drawing board to see if I can change the functionality a bit so that I render directly to pdf.

**Comment by HakanL** [comment]
Yeah, that's what I've seen as well, so at the moment there aren't any better alternatives, so this project is still valid (and to be honest, as long as it generates the PDF from your HTML in the way you want to, it doesn't have to be upgraded). I'm going to close this issue as there's no action.
