### ISSUE TITLE
How to directly pass parameters to wkhtmltopdf without using objects

### ISSUE THREAD

**Issue by Tilation** [HakanL/WkHtmlToPdf-DotNet#118]
I have a class that generates the parameter string that gets passed to wkhtmltopdf, now we opted to migrate to this package, but I cant seem to find a way to directly pass this string to the package, it only lets me use the object oriented aproach.

How can I send a string that contains all convert-related parameters to wkhtmltopdf?
For example: `--print-media-type --enable-local-file-access --page-size * --footer-center "asd" --zoom 1` etc

**Comment by HakanL** [comment]
There no support since this project is not calling the command-line version of wkhtmltopdf, we're actually loading the DLL and making method calls into it. So you need to use the object oriented approach.

**Comment by Tilation** [comment]
@HakanL Okay, I mostly got around, but I need the OOP alternative for `--print-media-type` and I can't find it anywhere. Where is it?
