### ISSUE TITLE
How can I include CSS like Bootstrap in my HTML so that I can observe the applied styles when generating a PDF?

### ISSUE THREAD

**Issue by AlexCorsega** [HakanL/WkHtmlToPdf-DotNet#120]
My HTML has CSS files I tried to link an external and internal CSS but its not working. When I generate the PDF, the styles is not applied to the PDF file.

**Comment by HakanL** [comment]
There's a setting called BlockLocalFileAccess which is probably the cause of this.

**Comment by AlexCorsega** [comment]
I set the BlockLocalFileAccess to false and still the applied styles is not showing in the PDF.

Here's my code:
![image](https://github.com/HakanL/WkHtmlToPdf-DotNet/assets/111210922/9125d63e-0058-4d66-9af0-f5fa7e023f8e)

Do you think there's a problem with it?

**Comment by HakanL** [comment]
Looks correct. What does your stylesheet reference look like? Maybe test it using the native wkhtmltopdf tool first to see if it works there.

**Comment by AlexCorsega** [comment]
Here's my stylesheet look like.

 <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
 <link rel="stylesheet" href="C:/Users/User/Downloads/bootstrap-5.3.2-dist/bootstrap-5.3.2-dist/css/bootstrap.css" />
 
 On top of that was an internal style of bootstrap in hope that It will work.
 I tested everything but the applied styles is not reflected to the PDF.

**Comment by HakanL** [comment]
I read somewhere that you need to use file:// for the links, try that. If that doesn't work then try the native library and report the issue there, since this project here is just a wrapper.

**Comment by AlexCorsega** [comment]
Okay thank you for your help.
