### ISSUE TITLE
CSS defined in <style> not respected?

### ISSUE THREAD

**Issue by mark-attridge** [HakanL/WkHtmlToPdf-DotNet#136]
My project generates an HTML with a <head> and <body>.  In the <head>, I have some custom css defined in using <style>, when I view the HTML on a page, it renders as I expect, but the output to PDF doesn't seem to respect any of that styling.  Any suggestions?

**Comment by HakanL** [comment]
This project is just a wrapper of the wkhtmltopdf library, we don't do anything with the input or output content, so perhaps it's better to open an issue in that project. In general there are some differences between HTML in a browser and PDF.

**Comment by mark-attridge** [comment]
Hmm ok.  I was experimenting also with PuppeteerSharp, and it handled my
styling perfectly.

I will follow-up with wkhtmltopdf and see if they can assist.

**Comment by HakanL** [comment]
It's probably using a different rendering engine.

**Comment by ERYEMGOUBI** [comment]
The reason why u can't view your work as you anticipate could be wkhtmltopdf doesn't support CSS such opaticy or rotation....

**Comment by mark-attridge** [comment]
I have abandoned using wkhtmltopdf or any wrappers, and have gone in a different direction with the project and finding more success in getting the required results.

**Comment by HakanL** [comment]
@mark-attridge Makes sense, using a wrapper has its downsides. Just for reference, can you share what project/product you went with, I assume you're still doing HTML to PDF?

**Comment by mark-attridge** [comment]
We decided to go with PuppeteerSharp in a C# project, which is deployed as an Azure Container App.

**Comment by HakanL** [comment]
I see, is that primarily a wrapper/api into an installation of Chrome/Firefox or did I missunderstand the description?

**Comment by HakanL** [comment]
I wish there was a fully managed HTML to PDF package :)
