### ISSUE TITLE
Tests crashing on linux but not windows

### ISSUE THREAD

**Issue by drdamour** [HakanL/WkHtmlToPdf-DotNet#14]
using dotnet test have no issues on windows hosts, but on the ubuntu-latest in azure devops pipeline consistently get this.

i'm sure i'm doing something wrong...just not sure what.

```

The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DinkToPdf.PdfTools.Dispose(Boolean disposing)
   at DinkToPdf.PdfTools.Finalize()

```

**Comment by HakanL** [comment]
I pushed a potential fix (untested), can you please test it for me?

**Comment by drdamour** [comment]
off this project for now, so won't be able to get back to it for some time

**Comment by HakanL** [comment]
Ok, no problem. Do you remember what unit tests you were running, in your own project? Because there aren't any unit tests in this repo. Or you get this error when consuming this NuGet package in a unit test?

**Comment by HakanL** [comment]
Based on the feedback from #18 I believe this has been fixed. I'm closing this issue, feel free to re-open if it's still an issue.
