### ISSUE TITLE
EF Core migrations fails after adding this package

### ISSUE THREAD

**Issue by andbjer** [HakanL/WkHtmlToPdf-DotNet#18]
We currently use this package to generate PDFs from HTML in a .NET Core Web API and it has been working great. 

When I try to add a new EF Core migration an unhandled exception is thrown in this package:

```bash
dotnet ef migrations add <name> 
Build started...
Build succeeded.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DinkToPdf.PdfTools.Dispose(Boolean disposing)
   at DinkToPdf.PdfTools.Finalize()
```

In `Startup.cs` I have added the `IConverter` as a singleton:

```cs
    .AddSingleton<IConverter>(new SynchronizedConverter(new PdfTools()))
```

Migrations does not work in either Windows or Mac. 

Related: #14

**Comment by HakanL** [comment]
Please see if the fix I just pushed solved the issue.

**Comment by andbjer** [comment]
What's the easiest way for me to test this? 

I've pulled down the code from the repository and added the project to my solution. I added every runtime manually in the same folder structure as it is listed in `DinkToPdf.csproj`:

```
    <None Include="runtimes\linux-x64\native\libwkhtmltox.so" Pack="true" PackagePath="runtimes\linux-x64\native" />
    <None Include="runtimes\linux-x86\native\libwkhtmltox.so" Pack="true" PackagePath="runtimes\linux-x86\native" />
    <None Include="runtimes\osx-x64\native\libwkhtmltox.dylib" Pack="true" PackagePath="runtimes\osx-x64\native" />
    <None Include="runtimes\win-x64\native\wkhtmltox.dll" Pack="true" PackagePath="runtimes\win-x64\native" />
    <None Include="runtimes\win-x86\native\wkhtmltox.dll" Pack="true" PackagePath="runtimes\win-x86\native" />
```

Now I am getting this error when i try to generate a PDF:
```
System.DllNotFoundException: Unable to load shared library 'wkhtmltox' or one of its dependencies
```

**Comment by adamhathcock** [comment]
You probably shouldn't even be loading this in EFCore migration.

Change your DI definition to be lazy:
```
services.AddSingleton<IConverter>(x => new SynchronizedConverter(new PdfTools()))
```

**Comment by HakanL** [comment]
I uploaded a pre-release to NuGet, try that. https://www.nuget.org/packages/Haukcode.DinkToPdf/1.1.3-test-dispose-fix

**Comment by andbjer** [comment]
Tested the pre-release and migrations is working again. Thank you!

I also tested the suggestion by @adamhathcock before upgrading to the pre-release. This also solved my problem.

Thank you both!

**Comment by HakanL** [comment]
Ah, perfect, thanks for the quick feedback @andbjer ! Please use the new [repo ](https://www.nuget.org/packages/Haukcode.WkHtmlToPdfDotNet), version 1.2 which includes this fix.
