### ISSUE TITLE
Upgrade wkhtmltopdf binaries to version 0.12.6

### ISSUE THREAD

**Issue by HakanL** [HakanL/WkHtmlToPdf-DotNet#19]
New release: https://wkhtmltopdf.org/downloads.html

Should also document how to put together the binaries release for this project.

**Comment by thangnaozay** [comment]
Can you help me get *.so file of 0.12.6. I try to use of amazon, arc, and centOS but all fail. In your runtime folder of 0.12.5, I can use this *.so file for my app.

**Comment by HakanL** [comment]
I haven't tried 0.12.6 yet, but there's some incompatibility issues. Maybe use the 0.12.5 for now since I have pre-built tested binaries that that version? But if you want to try to build binaries for 0.12.6 and you can get it to work I appreciate any help.

**Comment by thangnaozay** [comment]
0.12.5 can not generate TOC so I need to upgrade to 0.12.6 but I don't know how to get the newest *.so file from https://wkhtmltopdf.org/downloads.htm, I try some case like the image below but all not work.

https://user-images.githubusercontent.com/13974409/95038107-93207a00-06f7-11eb-80d9-bc2db6b04707.png

Can you help me to give exactly a link to download the *.so file of 0.12.6 version?
Thanks!

**Comment by HakanL** [comment]
I'm sorry, I haven't used 0.12.6 yet, so I don't know which files to use.

**Comment by thangnaozay** [comment]
So, could you give me the name of linux (amazon, arc or cenOS) that you get .so file of 0.12.5?

**Comment by HakanL** [comment]
I couldn't remember, but I've determined now that I used wkhtmltox_0.12.5-1.stretch_amd64.deb and wkhtmltox_0.12.5-1.stretch_i386.deb for the 0.12.5 binaries.

**Comment by HakanL** [comment]
I've updated to 0.12.6, but I'm not 100% sure I got it right, I can't remember exactly what I did last time. @thangnaozay if you can help me test that would be awesome. NuGet package: https://www.nuget.org/packages/Haukcode.WkHtmlToPdfDotNet/1.3.0-test-0.12.6 and the code is in a branch called `test-0.12.6`.

**Comment by thangnaozay** [comment]
Great!!! It works well on Azure Linux. Thanks for your quick response and support!!!

**Comment by HakanL** [comment]
Version 1.3.0 of this package is released, including binaries for 0.12.6
