### ISSUE TITLE
Not working with many request.

### ISSUE THREAD

**Issue by thanhnamrei** [HakanL/WkHtmlToPdf-DotNet#27]
- I used it for asp.net core api to generation pdf,  but the first request work ok, but the second timeout in  byte[] pdf = converter.Convert(doc);
get 1: api/generatePdf response OK
get again:  api/generatePdf timeout

**Comment by HakanL** [comment]
Which converter are you using? Make sure you use the SynchronizedConverter

**Comment by thanhnamrei** [comment]
I use var converter = new SynchronizedConverter(new PdfTools());

**Comment by thanhnamrei** [comment]
> Which converter are you using? Make sure you use the SynchronizedConverter

i use var converter = new SynchronizedConverter(new PdfTools());

**Comment by HakanL** [comment]
Ok, yes, that is correct. See if you can create a unit test in the project to reproduce your issue.

**Comment by thanhnamrei** [comment]
> Ok, yes, that is correct. See if you can create a unit test in the project to reproduce your issue.
> […](#)
> On Nov 17, 2020, at 8:26 PM, thanhnamrei ***@***.***> wrote: ﻿ Which converter are you using? Make sure you use the SynchronizedConverter i use var converter = new SynchronizedConverter(new PdfTools()); — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HakanL** [comment]
Also make sure you're not creating a new converter every time, you should only create it once per process. See the ASP.NET example.

**Comment by thanhnamrei** [comment]
> Also make sure you're not creating a new converter every time, you should only create it once per process. See the ASP.NET example.

oh! thanks u. I tried it.
