### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by huysentruitw** [HakanL/WkHtmlToPdf-DotNet#30]
Hi, I'd like to collaborate a bit on this project.

Things I'd like to improve:
* limit API surface (now everything is public, even DllImports), I'd like to strip this down to the bare minimum
* see if we can improve memory handling
* improve performance
* start using SemVer + git flow for versioning
* setup github actions for automatic CI/CD

Perhaps this could all go in as a next major version 2.0. Are you open to contributors and willing to deviate away from DinkToPdf? I could create a fork and call it a day, but it's better to start with an existing user-base for validation.

**Comment by HakanL** [comment]
Hi @huysentruitw, thanks for your offer (and sorry about the delay in getting back to you).
I think your suggestions are great and would love some help. I don't mind to deviate from DinkToPdf, I forked it just for a project where I needed support for .NET Core and then I finally renamed it to be more "professional".
I have created Github actions for some other OSS I maintain, it could probably be a good starting point, I can look into that. I wasn't able to get auto versioning working well for that, happy to work with you to figure out a solid solution.

**Comment by HakanL** [comment]
@huysentruitw Feel free to submit PRs for any changes you'd like to see. I've taken steps to deviate from DinkToPdf and implemented Github Actions, so it should be in a good state now to do the changes you suggest. I'm closing this ticket for now since it's more of a question.
