### ISSUE TITLE
How can i get total page and current page before convert html to pdf?

### ISSUE THREAD

**Issue by ThanhCuD** [HakanL/WkHtmlToPdf-DotNet#35]
Ex : instead i use 
- HeaderSettings = { FontName = "Arial", FontSize = 9, Right = "Page [page] of [toPage]", Line = true } this always appear on header 
i want to get page and total page to display in another place

**Comment by HakanL** [comment]
I'm not sure, since this is just a wrapper around the parent project ([wkhtmltopdf](https://wkhtmltopdf.org/)) I think you need to look into that documentation.
