### ISSUE TITLE
runtimes

### ISSUE THREAD

**Issue by FS-FIT** [HakanL/WkHtmlToPdf-DotNet#37]
good job!

Can you please commit the runtimes ?

Thanks and kind regards

**Comment by FS-FIT** [comment]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/47035321/113772086-802d4780-9724-11eb-9e57-5b65b555e423.png">

**Comment by HakanL** [comment]
I don't believe they belong in the main repo. They are linked as a submodule though, so if you checkout with submodules then you'll get them. (Linked to this repo: https://github.com/HakanL/WkHtmlToPdf-DotNet-BIN)
