### ISSUE TITLE
disable-smart-shrinking is not implemented

### ISSUE THREAD

**Issue by mmuniesa** [HakanL/WkHtmlToPdf-DotNet#40]
Hello,

We are missing the **disable-smart-shrinking** setting. We have tested this using the wkthmltopdf library and it does work but there is no setting in the wrapper for this.

Could you advise on how to solve this problem please?

Thank you!

**Comment by HakanL** [comment]
You can probably just add the setting and submit a PR.

**Comment by mmuniesa** [comment]
Hi @HakanL,

We have tried adding the following setting to the ObjectSettings class but it doesn't seem to take affect.

        [WkHtml("disableSmartShrinking")]
        public bool? DisableSmartShrinking { get; set; }

Does it look correct?

Thank you

**Comment by HakanL** [comment]
What is the exact name in wkhtml for this setting? It has to be an exact match and on the correct settings object.

**Comment by HakanL** [comment]
A quick search seems to indicate that it's called "web.enableIntelligentShrinking" and it's on the page settings object. https://wkhtmltopdf.org/libwkhtmltox/pagesettings.html

**Comment by HakanL** [comment]
Oh, it's already there, hehe. Check out EnableIntelligentShrinking on the WebSettings.

**Comment by mmuniesa** [comment]
thanks @HakanL :) we have seen it as well and it works!!
