### ISSUE TITLE
Blazor WASM

### ISSUE THREAD

**Issue by boukenka** [HakanL/WkHtmlToPdf-DotNet#41]
Hello,

Will it work on a blazor wasm? I guess not.
Getting the error below. 

_Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported._

Thanks for any answer.

**Comment by HakanL** [comment]
This project is just a wrapper for the native WkHtmlToPdf library, I doubt Blazor allows native DLLs.

**Comment by boukenka** [comment]
Thank you for your answer
