### ISSUE TITLE
Qt: Could not initialize OLE (error 80010106)

### ISSUE THREAD

**Issue by gnahziak** [HakanL/WkHtmlToPdf-DotNet#43]
RUN TestWebServer appear this error tip  but the pdf has been generated .Does this error have any effect?

![image](https://user-images.githubusercontent.com/16639887/125388703-91948880-e3d2-11eb-82ce-f3efa780bffe.png)

**Comment by HakanL** [comment]
No, it’s just a warning from the native library.
