### ISSUE TITLE
Blank Pages being inserted in large PDFs

### ISSUE THREAD

**Issue by CaseyLemieux** [HakanL/WkHtmlToPdf-DotNet#44]
WkHtmlToPdf-DotNet seems to be inserting blank pages into pdfs being converted to byte arrays if its used consecutively. I don't know if this is an issue with the converter or something else. I am generating student ids in pdfs from html templates and CSS. If I generate them individually it works correctly and is formatted right.  However if I generate a large number of them it starts inserting blank pages between the front and back of the ids that print fine when doing them individually. I tried limiting the to 25 students thus 50 page pdfs which makes the first 50 print correctly but after that it starts inserting blank pages. Maybe an issue with calling the converter back to back? Any help would be appreciated.

**Comment by HakanL** [comment]
Try to use the native library directly and see if you can reproduce the problem. Not likely an issue with this .NET Wrapper.
