### ISSUE TITLE
Add TargetFramework .netstandard2.1 to DinkToPdf.csproj

### ISSUE THREAD

**Issue by AnuragBhv** [HakanL/WkHtmlToPdf-DotNet#50]
Though none of newly added APIs to .net standard 2.1 might not be used internally it would make this project ready for upgrade to support new frameworks like .Net 5 and 6.

Reference article https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/.

**Comment by HakanL** [comment]
.NET 5 and 6 will work fine with .NET Standard 2.0 as well, it's just an identifier what the library expects from the framework/runtime.
