### ISSUE TITLE
Table of Content Headline

### ISSUE THREAD

**Issue by bernardosimonetto** [HakanL/WkHtmlToPdf-DotNet#57]
I really like this package!

Is there any possibility to change the TOC-Headline text?

**Comment by HakanL** [comment]
I'm not sure, there is an object for TOC settings, maybe it has to be added there. Please see if you can find the settings for the native library and add them to TableOfContentsSettings in a PR if you can.

**Comment by HakanL** [comment]
This has been pushed to master.
