### ISSUE TITLE
Should Update Example

### ISSUE THREAD

**Issue by DanielKeeley** [HakanL/WkHtmlToPdf-DotNet#59]
Hi,

Thanks for this nuget.
Just wanted to let you know if you try to convert two documents to pdf in the same call it will hang on the 2nd conversion, with no error.
You need to Dispose() the converter after it has been used.

            `var converter = new BasicConverter(new PdfTools());
            var bytes = converter.Convert(doc);
            converter.Dispose();
            return bytes;`

**Comment by HakanL** [comment]
Thanks for your input. The examples came from the original repo, but I'm happy to accept a PR to fix anything you see!

**Comment by DanielKeeley** [comment]
ah ok i'm just still trying to see why this is happening, might just be me actually

**Comment by HakanL** [comment]
Ok, could it be that you're trying to do something concurrently (multi-threaded)? The native library requires all calls to be single-threaded, so you need to use the SynchronizedConverted.

**Comment by DanielKeeley** [comment]
yep that was it, it's all working now, but I also had to put the converter as static outside of the method to have both pdfs convert properly:
![image](https://user-images.githubusercontent.com/87320487/140064620-c899639c-74df-490e-9666-38ab3ae85c9a.png)

**Comment by HakanL** [comment]
Yep, the converter shouldn't be re-created for each request.
