### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by olnor18** [HakanL/WkHtmlToPdf-DotNet#71]
Using this library with user-supplied input in any way, even if just used to fill out a template could lead to major vulnerabilities. Do not use this library with user-supplied input until this is mitigated. Please reach out so this can get patched. More info [here](https://github.com/rdvojmoc/DinkToPdf/issues/154).

**Comment by HakanL** [comment]
This is just a wrapper around a native library, if such vulnerability exists then you should open that with the native library (wkhtmltopdf) instead.

**Comment by HakanL** [comment]
Got it, done! Thanks!
