### ISSUE TITLE
Missing `HeaderSettings.HtmlContent`

### ISSUE THREAD

**Issue by asbjornu** [HakanL/WkHtmlToPdf-DotNet#75]
`ObjectSettings` has an `HtmlContent` property which provides a useful way to assign HTML content without having to store it on disk anywhere. The `HeaderSettings` class has an `HtmlUrl` property, but lacks an `HtmlContent` property. It would be nice if `HeaderSettings.HtmlContent` was made available as an alternative to `HeaderSettings.HtmlUrl`.

**Comment by HakanL** [comment]
Good suggestion, feel free to offer a PR!

**Comment by HakanL** [comment]
Actually, I don't think the parent native library supports this, so without support there it can't be supported in this wrapper. Best would probably to raise an issue/feature request with wkhtmltopdf.
