### ISSUE TITLE
How to make the cover  

### ISSUE THREAD

**Issue by MrQLEO** [HakanL/WkHtmlToPdf-DotNet#76]
I want to make a cover for the document  ，But there seems to be no such method。
and
is it possible to support asynchronous loading of data to html

**Comment by HakanL** [comment]
I'm not sure, the best is probably to check the capabilities of the parent native library [wkhtmltopdf](https://wkhtmltopdf.org/) and if there's a feature missing in this wrapper then we gladly accept PRs.

**Comment by MrQLEO** [comment]
> I'm not sure, the best is probably to check the capabilities of the parent native library [wkhtmltopdf](https://wkhtmltopdf.org/) and if there's a feature missing in this wrapper then we gladly accept PRs.

As much as I want to do something
emm..... but  I'm just a beginner
And  I also found a problem error occurs when using it again
> `bool converted = Tools.DoConversion(converter);`
![image](https://user-images.githubusercontent.com/44421477/164710934-e32b791b-75c9-48ee-820a-1d661638431e.png)
But I don't know how to solve

**Comment by HakanL** [comment]
Try to run the examples, it sounds like you used it incorrectly, you can get exceptions like this when dealing with native libraries.

**Comment by HakanL** [comment]
@MrQLEO See this issue for hints on what may cause the exception: https://github.com/HakanL/WkHtmlToPdf-DotNet/issues/78

**Comment by MrQLEO** [comment]
> @MrQLEO有关可能导致异常的提示，请参阅此问题：#78

Oh,thanks,you are very nice
I think I get it

**Comment by MrQLEO** [comment]
> @MrQLEO See this issue for hints on what may cause the exception: #78

Oh,thanks,you are very nice
I think I get it
