### ISSUE TITLE
Does the latest version support.net6?

### ISSUE THREAD

**Issue by cd-linxi** [HakanL/WkHtmlToPdf-DotNet#81]
Does the latest version support.net6?

"iCCP: known incorrect sRGB profile" what's the reason？

**Comment by cd-linxi** [comment]
![image](https://user-images.githubusercontent.com/18459074/178235649-c30ca8a6-5041-4f48-9122-9e3376d824c2.png)
There is such a mistake, please tell me the reason?

**Comment by cd-linxi** [comment]
Why y do you include base64 images in your HTML, but the resulting PDF does not contain images?

**Comment by HakanL** [comment]
Please note that this project is just a wrapper around the native wkhtmltopdf library. Any warnings during generation of the PDF is just passed from the native library, and if there are issues with the HTML then it's best to run the native command line tool from https://wkhtmltopdf.org/ and go from there in your troubleshooting. It is possible somebody here can help you with your HTML, but then you need to include the actual HTML. From your screenshot it looks like you're trying to access local files/images, which is disabled by default.
