### ISSUE TITLE
The HTML file contains webP images, which cannot be displayed after the PDF file is generated. 

### ISSUE THREAD

**Issue by cd-linxi** [HakanL/WkHtmlToPdf-DotNet#82]
Webp images in HTML should be displayed in the browser.
The exported PDF cannot be displayed.

**Comment by HakanL** [comment]
It's something you need to bring up with the parent/native library, as mentioned in another ticket, this is just a wrapper of the native library, the PDF generation does not happen in this project. A quick search gives us this: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3977
