### ISSUE TITLE
Linux Packages missing on Alphine are there alternatives?

### ISSUE THREAD

**Issue by j0nimost** [HakanL/WkHtmlToPdf-DotNet#84]
While building a docker image running Alpine I came across a rude shock that the suggested package

`libc6-dev` does not exist in its repository. Is there a walk-around to this issue?

**Comment by HakanL** [comment]
It may be called something else in different distributions, it's outside the scope of this .NET package.

**Comment by j0nimost** [comment]
Found the Solution here: https://stackoverflow.com/a/70414848/7022936
