### ISSUE TITLE
Tables than span across a page break are not properly split

### ISSUE THREAD

**Issue by jwassel** [HakanL/WkHtmlToPdf-DotNet#86]
First - love this library! 

The only issue I've come across is that when I have a long table that spans at least one, potentially multiple pages, the table row at the page break usually gets cut in half (sometimes it lines up perfectly and there's no issue, but that's just up to chance).

I've tried implementing the header/footer options, the margin options, and also tried some CSS I've seen on forums for the DinkToPDF library, like using page-break-inside, but nothing seems to help. 

Please let me know if I'm missing the easy solution as well.

**Comment by HakanL** [comment]
Unfortunately this project is just a wrapper around the native wkhtmltopdf, so the appropriate place to report the issue is on their site, since this wrapper doesn't do anything with the rendering.

**Comment by jwassel** [comment]
Thanks for the update!
