### ISSUE TITLE
Application in Blazor Server?

### ISSUE THREAD

**Issue by wilsonmaf** [HakanL/WkHtmlToPdf-DotNet#93]
I'm sorry in advance if this is a stupid question!

Do people use this library on their Blazor Server?

I know this is an awesome tool. 

But I'm quite new to .NET and can't figure out how to implement wkhtmltopdf in my project.

**Comment by HakanL** [comment]
I'm not familiar with Blazor Server, but my guess is that it will **not** work, since this package is a wrapper around a native library.

**Comment by wilsonmaf** [comment]
Cheers mate.
I guess I'll find a new library then.
