### ISSUE TITLE
Html Header/Footer support

### ISSUE THREAD

**Issue by JustasKvederis** [HakanL/WkHtmlToPdf-DotNet#94]
Hello is there any way to add html to Header/Footer ? Since setting htmlURL doesn't do anything for me, and The best option would be just to specify the code directly. Is there any way to parse it ?

**Comment by HakanL** [comment]
The only option is via the HtmlUrl property, but there may be issues loading the URL, it may have to be absolute (not sure what the requirements are). This is all controlled by the native library, see this for reference: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/5015
