### ISSUE TITLE
Weird errors that I can't pin point

### ISSUE THREAD

**Issue by JustasKvederis** [HakanL/WkHtmlToPdf-DotNet#95]
Hello, thanks for your last response (it was very helpful). This time I am having a different issue. I am writing a simple console application that generates PDF's.... And it works, but it still throws these two errors: 
Qt: Could not initialize OLE (error 80010106)
QWaitCondition: Destroyed while threads are still waiting

One is thrown at the beginning of the execution only once (no matter how many times I generate files), after this line:
            byte[] pdft = pdfConverter.Convert(doct);

 and the one at the end of the execution.

For the second Error I tried to add Thread.sleep, to see if I keep the console alive for longer it might help, but it did not. Do you have any insights into it ?

**Comment by HakanL** [comment]
There is a console example in the repo, have you tried that?

**Comment by JustasKvederis** [comment]
I just had a look, but it seems identical in the most important areas. I create a Basicconverter with pdf tools, then I create the document with the settings, which are similar and I try to convert and i get that error as I mentioned it still works it creates the pdf, but I was wondering how to fix the errors/warnings, but if they are harmless I guess I can just ignore them.

**Comment by HakanL** [comment]
You will get some warnings, which is normal, but you mentioned that errors were thrown. As long as the document is generated then you should be good.

**Comment by erickvalderrama** [comment]
> I just had a look, but it seems identical in the most important areas. I create a Basicconverter with pdf tools, then I create the document with the settings, which are similar and I try to convert and i get that error as I mentioned it still works it creates the pdf, but I was wondering how to fix the errors/warnings, but if they are harmless I guess I can just ignore them.

I hope this help you:

First: 

![image](https://user-images.githubusercontent.com/28714005/201521449-ec272eb9-bf8a-4c12-b228-cd3032892a02.png)

Then:

![image](https://user-images.githubusercontent.com/28714005/201521479-a7193b96-8fa7-47b8-9bc3-028d7e49fd6f.png)

After:

![image](https://user-images.githubusercontent.com/28714005/201521501-e1ede71a-1047-42d1-b072-7b08a7d03275.png)

**Comment by HakanL** [comment]
Is it an exception, or a warning? If it's an exception, what is the exception?

**Comment by erickvalderrama** [comment]
No, it is not a exception.  Just it is freezing app when we creating instances of IConvert inside functions or  methods, so it just allow call IConvert once.

**Comment by HakanL** [comment]
Do you mean it's hanging when you **call** .Convert, or when you **create** an instance of SynchronizedConverter? This doesn't sound like it's related to this issue, that was opened due to the warnings the library outputs.

**Comment by JustasKvederis** [comment]
> Is it an exception, or a warning? If it's an exception, what is the exception?

Sorry for the late reply, yes it's just a warning, it works if you ignore the warnings.

**Comment by JustasKvederis** [comment]
> No, it is not a exception. Just it is freezing app when we creating instances of IConvert inside functions or methods, so it just allow call IConvert once.

Sorry it does not freeze and it does work just with the exceptions. But since it's a console application it doesn't really have DI, I can't add it to the builder. There are work arounds, but I doubt that it's the issue.

**Comment by HakanL** [comment]
Ok, yes, you need to ignore the warnings, because they are just warnings about the environment (and they are coming from the native library, so not something we can affect in this wrapper project.

Ok, it's a little confusing when you say exceptions. Exceptions stop execution and prevent the function to work. Warnings (that are just outputted to logs) are not exceptions. So if I understand you there are no exceptions, everything works, nothing freezes? There are examples in this repo on how to call this from console without using DI.

**Comment by JustasKvederis** [comment]
> Ok, yes, you need to ignore the warnings, because they are just warnings about the environment (and they are coming from the native library, so not something we can affect in this wrapper project.
> 
> Ok, it's a little confusing when you say exceptions. Exceptions stop execution and prevent the function to work. Warnings (that are just outputted to logs) are not exceptions. So if I understand you there are no exceptions, everything works, nothing freezes? There are examples in this repo on how to call this from console without using DI.

Yeah there are no exceptions, sorry for the incorrect terminology. Yes everything works and I saw the example I was just answering erick, because he suggested DI. Thanks, for your responses all is well.
