### ISSUE TITLE
System.AccessViolationException' occurred in WkHtmlToPdfDotNet.dll

### ISSUE THREAD

**Issue by crmmvio** [HakanL/WkHtmlToPdf-DotNet#96]
When I try to generate a pdf twice in a row the following error occurs:

Erro An unhandled exception of type 'System.AccessViolationException' occurred in WkHtmlToPdfDotNet.dll: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

`
var htmlContent = await this.RenderViewAsync("PrintCoverSheet", viewModel, false);

            using (var converter = new SynchronizedConverter(new PdfTools()))
            {
                converter.PhaseChanged += Converter_PhaseChanged;
                converter.ProgressChanged += Converter_ProgressChanged;
                converter.Finished += Converter_Finished;
                converter.Warning += Converter_Warning;
                converter.Error += Converter_Error;

                var doc = new HtmlToPdfDocument()
                {
                    GlobalSettings = {
                        PaperSize = PaperKind.A4,
                        ColorMode = ColorMode.Color,
                        Orientation = Orientation.Portrait,
                        Margins = new MarginSettings(5,5,5,5) {Unit = Unit.Millimeters}
                    },

                    Objects = {
                        new ObjectSettings()
                        {
                            WebSettings = { DefaultEncoding = "utf-8" },
                            UseExternalLinks = false,
                            UseLocalLinks = true,
                            IncludeInOutline = true,
                            Page = Url.AbsoluteAction("GeraFolhaRosto", "FolhaRosto", new{id= viewModel.Id})
                        }
                    }
                };

                dataPdf = converter.Convert(doc);
            }

            Response.Headers.Add("content-disposition", $"attachment; filename={filename}");
            return File(dataPdf, "application/pdf", filename);
`
![Erro-WkHtmlToPdfDotNet](https://user-images.githubusercontent.com/2079957/210634055-462c6a06-10b5-4cb8-9671-1ecfc59741f8.png)

**Comment by HakanL** [comment]
You need to only hold a singleton of the SynchronizedConverter.

**Comment by crmmvio** [comment]
In the Startup file already has

services.AddSingleton(typeof(IConverter), new SynchronizedConverter(new PdfTools()));

**Comment by HakanL** [comment]
Then you should use that, instead of creating a new instance:
`using (var converter = new SynchronizedConverter(new PdfTools()))`

**Comment by crmmvio** [comment]
see above my code is exactly like this

**Comment by HakanL** [comment]
Yes, that's what's wrong, you should **NOT** create a new instance, instead you should use the singleton.

**Comment by crmmvio** [comment]
You would have an example of correct use, this one I got from the git documentation

**Comment by HakanL** [comment]
We do, it's right here: https://github.com/HakanL/WkHtmlToPdf-DotNet/blob/master/src/TestWebServer/Controllers/ConvertController.cs

**Comment by crmmvio** [comment]
ok now i understand, use by IOC, tks!!
