### ISSUE TITLE
doesn't calculate page size correctly

### ISSUE THREAD

**Issue by citypanther** [HakanL/WkHtmlToPdf-DotNet#97]
first, great work!
I found some issues while using it. It sometimes cut a line in two parts, each page display a part of the line. I guess it because the pdf file generated is treated as image? any solutions on the issue?
and another suggestion is that can you provide a function that allows the user insert a page break?  that would be perfect !!

**Comment by HakanL** [comment]
This project is just a wrapper for wkhtmltopdf that does all the heavy lifting, so you need to open this issue with that project instead.
