### ISSUE TITLE
Add ability to process pdf generation on multiple threads

### ISSUE THREAD

**Issue by t00** [HakanL/WkHtmlToPdf-DotNet#98]
Current SynchronizedConverter implementation seems to not allow specifying number of threads used when generating pdfs. Allowing multiple instances of whhtmltopdf and using them in parallel would make the library several times more performant if needed.

**Comment by HakanL** [comment]
It's my understanding that the native library doesn't support multi-threading, and it's loaded in the main AppDomain, so I don't think it will be as easy as just setting up a number of threads. But if you can figure out how to load multiple copies of the native library then it may work.
