### ISSUE TITLE
How can I set html code with css in  header

### ISSUE THREAD

**Issue by Su1N** [HakanL/WkHtmlToPdf-DotNet#99]
I want to make my pdf's header also have css.

**Comment by HakanL** [comment]
I don't think that's supported, but it's best to raise this question with wkhtmltopdf as this project is simply a wrapper for .NET around the native library that does all the heavylifting.

**Comment by FransdeJong** [comment]
@Su1N 
I managed to style the header and footer using a global css file that I added in the Objectsettings like this:


`new ObjectSettings
                        {
                            PagesCount = true,
                            HtmlContent = htmlString,
                            WebSettings =
                            {
                                DefaultEncoding = "utf-8",
                                LoadImages= true,
                                PrintMediaType = false,
                                **UserStyleSheet = pdfViewModel.StyleSheet**
                            },
                            HeaderSettings =
                            {
                                Spacing = 20,
                                HtmlUrl = pdfViewModel.HeaderUrl
                            },
                            FooterSettings =
                            {
                                Spacing= 30,
                                HtmlUrl = pdfViewModel.FooterUrl
                            }
                        }`
